server:
  port: 4003
spring:
  datasource:
    url: jdbc:hsqldb:mem:webrobot-lookup
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.HSQLDialect
  output:
    ansi:
      enabled: always
  cloud:
    stream:
      bindings:
        new-lookups:
          content-type: application/json
logging:
  level:
    org:
      hibernate:
        type: TRACE