server:
  port: 4003
spring:
  datasource:
    url: jdbc:hsqldb:mem:webrobot-lookup
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    database-platform: org.hibernate.dialect.HSQLDialect
  output:
    ansi:
      enabled: always
  cloud:
    stream:
      bindings:
        new-lookups:
          content-type: application/json
        lookup-jobs:
          group: lookup-service
logging:
  level:
    root: info